apiVersion: nais.io/v1alpha1

kind: Application

metadata:
  name: prim-bemanningsbehov
  namespace: pim
  labels:
    team: pim

spec:
  env:
    - name: BEMANNINGSBEHOV_REST_URL
      value: https://bemanningsbehov.dev-fss-pub.nais.io
    - name: FSS_CONTEXT
      value: dev-fss
  image: {{ image }}
  port: 3000
  ingresses:
    - https://prim-bemanningsbehov.dev.intern.nav.no
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - NAVident
          - azp_name
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: bemanningsbehov.dev-fss-pub.nais.io
  liveness:
    path: /api/isAlive
  readiness:
    path: /api/isReady
  replicas:
    min: 1
    max: 1
